things

diff --git a/bin/readlink-f b/bin/readlink-f
--- a/bin/readlink-f
+++ b/bin/readlink-f
@@ -3,22 +3,24 @@
 TARGET_FILE=$1
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
-  cd `dirname $TARGET_FILE`
-  TARGET_FILE=`basename $TARGET_FILE`
+  cd "$(dirname "$TARGET_FILE")"
+  TARGET_FILE="$(basename "$TARGET_FILE")"
 
   # Iterate down a (possible) chain of symlinks
   while [ -L "$TARGET_FILE" ]
   do
-      TARGET_FILE=`readlink $TARGET_FILE`
-      cd `dirname $TARGET_FILE`
-      TARGET_FILE=`basename $TARGET_FILE`
+      TARGET_FILE="$(readlink "$TARGET_FILE")"
+      cd "$(dirname "$TARGET_FILE")"
+      TARGET_FILE="$(basename "$TARGET_FILE")"
   done
 
   # Compute the canonicalized name by finding the physical path
   # for the directory we're in and appending the target file.
-  PHYS_DIR=`pwd -P`
-  RESULT=$PHYS_DIR/$TARGET_FILE
-  echo $RESULT
+  PHYS_DIR="$(pwd -P)"
+  RESULT="$PHYS_DIR/$TARGET_FILE"
+  echo "$RESULT"
+  exit 0
 else
-  readlink -f "$1"
+  echo "ERROR: not meant to be used in non-darwin OS's" 1>&2
+  exit 1
 fi
